### PR TITLE
feat: Swap out USSF logo SVG, EPR copy fix

### LINKED ISSUE #447: The beta USSF logos should be the full text logos
We currently have the abbreviated logos (USSF; file: ussf-logo-short.svg) at the top and bottom of the page. These should be the full text ones (United States Space Force; file: ussf-logo.svg).

### LINKED ISSUE #451: Change "Next EPR" language.
I can't believe I didn't catch this earlier. On the main page once you enter the beta, there is a "Next EPR" section under the Welcome message. Can we have that just say "Next Performance Report"? Officers, civilians and contractors don't have EPRs (Enlisted Performance Reports).

### PR DESCRIPTION
**Pull request by suzubara**
## Description 

Use an unabbreviated version of the USSF logo in the header & footer. Also changes the page header copy from "Next EPR" to "Next Performance Report"

Fixes #447 
Fixes #451 

## Review Notes

image

### CODE REVIEW

File: src/components/Logo/Logo.tsx [hunk 1]
```diff
@@ -1,6 +1,21 @@
...
+  darkBg = false,
+}: {
+  abbreviated?: boolean
+  darkBg?: boolean
+}) => {
+  if (darkBg) {
+    return (
+      <img
+        src="/assets/images/SpaceForce_Horizontal_Gradient_RGBmod-01.svg"
+        alt="United States Space Force"
```
Comment (abbyoung) [inline src/components/Logo/Logo.tsx:14]: looks like we need to update the unit tests w the alt text

Comment (suzubara) [reply src/components/Logo/Logo.tsx]: thanks!

**Review by abbyoung — APPROVED** [review]
