### PR TITLE
fix: Init analytics context from API data

### LINKED ISSUE #501: Analytics config is not being loaded into NextJS from environment
In order to send analytics data to Matomo, the MATOMO_URL and MATOMO_SITE_ID values must be defined in a given environment. However NextJS is not pulling these values into the application consistently.

To reproduce:
* In an incognito window, visit https://dev.ussforbit.us/login and view the browser JS console. You should _not_ see the error `ANALYTICS: No Matomo URL provided`
* In a regular or incognito browser window, login to the portal normally and after logging in, refresh the page. When you view the browser JS console you _should_ see the error `ANALYTICS: No Matomo URL provided`

Possible related issues/resources:
* https://github.com/vercel/next.js/issues/23033
* https://github.com/vercel/next.js/issues/22266
* https://github.com/vercel/next.js/issues/4024
* https://github.com/vercel/next.js/issues/6533

### PR DESCRIPTION
**Pull request by suzubara**
## Description 

This PR changes how the AnalyticsContext is initialized. Instead of using NextJS runtime variables (which produced inconsistent & confusing results), the analytics code makes a request to `/api/sysinfo` to query the Matomo URL & site ID in the browser. This lets us set those environment variables at runtime without having to worry about build variables. We may revisit this in the future if we start building images per-environment, but for now it should make the analytics init more consistent.

Fixes #501 

## Review Notes

* Log in to the portal and navigate to the beta landing page and/or the Sites & Applications page. Open the browser JS console and refresh the page. You should _not_ see the error `ANALYTICS: No Matomo URL provided`.

### CODE REVIEW

File: src/pages/api/sysinfo.ts [hunk 1]
```diff
@@ -10,5 +10,7 @@ export default function handler(req: NextApiRequest, res: NextApiResponse) {
     version: __VERSION__,
     buildId: __BUILD_ID__,
     nodeEnv: __NODE_ENV__,
+    analyticsUrl: process.env.MATOMO_URL,
```
Comment (suzubara) [inline src/pages/api/sysinfo.ts:13]: @abbyoung this info seemed appropriate to add to this existing endpoint, but let me know if you feel otherwise!!

**Review by abbyoung — APPROVED** [review]
